listResources = [
{"type": "image", "name": "imgBlockEmpty", "src": "resources/block_empty.png"},
{"type": "image", "name": "imgBlockEmptyProjection", "src": "resources/block_empty_projection.png"},

{"type": "image", "name": "imgStartGameLogo", "src": "resources/startgame.png"},
{"type": "image", "name": "imgGameBackground", "src": "resources/img_game_background.png"},
{"type": "image", "name": "imgBoardBackground", "src": "resources/img_board_bg.png"},
{"type": "image", "name": "imgLogo", "src": "resources/logo.png"},

{"type": "image", "name": "imgLeft", "src": "resources/left.png"},
{"type": "image", "name": "imgRight", "src": "resources/right.png"},
{"type": "image", "name": "imgDown", "src": "resources/down.png"},
{"type": "image", "name": "imgUp", "src": "resources/up.png"},

{"type": "image", "name": "imgLogoPansa", "src": "resources/pansacreations.png"},
{"type": "image", "name": "imgDesign", "src": "resources/design.png"},

{"type": "image", "name": "imgBlock0", "src": "resources/block_0.png"},
{"type": "image", "name": "imgBlock1", "src": "resources/block_1.png"},
{"type": "image", "name": "imgBlock2", "src": "resources/block_2.png"},
{"type": "image", "name": "imgBlock3", "src": "resources/block_3.png"},
{"type": "image", "name": "imgBlock4", "src": "resources/block_4.png"},
{"type": "image", "name": "imgBlock5", "src": "resources/block_5.png"},
{"type": "image", "name": "imgBlock6", "src": "resources/block_6.png"},

{"type": "image", "name": "img000", "src": "resources/000.png"},
{"type": "image", "name": "img001", "src": "resources/001.png"},
{"type": "image", "name": "img002", "src": "resources/002.png"},
{"type": "image", "name": "img003", "src": "resources/003.png"},
{"type": "image", "name": "img004", "src": "resources/004.png"},
{"type": "image", "name": "img005", "src": "resources/005.png"},
{"type": "image", "name": "img006", "src": "resources/006.png"},
{"type": "image", "name": "img007", "src": "resources/007.png"},
{"type": "image", "name": "img008", "src": "resources/008.png"},
{"type": "image", "name": "img009", "src": "resources/009.png"},

{"type": "image", "name": "chr0", "src": "resources/0.png"},
{"type": "image", "name": "chr1", "src": "resources/1.png"},
{"type": "image", "name": "chr2", "src": "resources/2.png"},
{"type": "image", "name": "chr3", "src": "resources/3.png"},
{"type": "image", "name": "chr4", "src": "resources/4.png"},
{"type": "image", "name": "chr5", "src": "resources/5.png"},
{"type": "image", "name": "chr6", "src": "resources/6.png"},
{"type": "image", "name": "chr7", "src": "resources/7.png"},
{"type": "image", "name": "chr8", "src": "resources/8.png"},
{"type": "image", "name": "chr9", "src": "resources/9.png"},

{"type": "image", "name": "chrA", "src": "resources/A.png"},
{"type": "image", "name": "chrB", "src": "resources/B.png"},
{"type": "image", "name": "chrC", "src": "resources/C.png"},
{"type": "image", "name": "chrD", "src": "resources/D.png"},
{"type": "image", "name": "chrE", "src": "resources/E.png"},
{"type": "image", "name": "chrF", "src": "resources/F.png"},
{"type": "image", "name": "chrG", "src": "resources/G.png"},
{"type": "image", "name": "chrH", "src": "resources/H.png"},
{"type": "image", "name": "chrI", "src": "resources/I.png"},
{"type": "image", "name": "chrJ", "src": "resources/J.png"},
{"type": "image", "name": "chrK", "src": "resources/K.png"},
{"type": "image", "name": "chrL", "src": "resources/L.png"},
{"type": "image", "name": "chrM", "src": "resources/M.png"},
{"type": "image", "name": "chrN", "src": "resources/N.png"},
{"type": "image", "name": "chrO", "src": "resources/O.png"},
{"type": "image", "name": "chrP", "src": "resources/P.png"},
{"type": "image", "name": "chrQ", "src": "resources/Q.png"},
{"type": "image", "name": "chrR", "src": "resources/R.png"},
{"type": "image", "name": "chrS", "src": "resources/S.png"},
{"type": "image", "name": "chrT", "src": "resources/T.png"},
{"type": "image", "name": "chrU", "src": "resources/U.png"},
{"type": "image", "name": "chrV", "src": "resources/V.png"},
{"type": "image", "name": "chrW", "src": "resources/W.png"},
{"type": "image", "name": "chrX", "src": "resources/X.png"},
{"type": "image", "name": "chrY", "src": "resources/Y.png"},
{"type": "image", "name": "chrZ", "src": "resources/Z.png"},

{"type": "sound", "name": "tile_move", "src": "resources/tile_move.ogg"},
{"type": "sound", "name": "tile_rotate", "src": "resources/tile_rotate.ogg"},
{"type": "sound", "name": "tile_settle", "src": "resources/tile_settle.ogg"},

{"type": "music", "name": "tile_music", "src": "resources/tile_music.ogg"}

]
