listResources = [
{"type": "image", "name": "imgBlockEmpty", "src": "resources/graphics/block_empty.png"},
{"type": "image", "name": "imgBlockEmptyProjection", "src": "resources/graphics/block_empty_projection.png"},

{"type": "image", "name": "imgStartGameLogo", "src": "resources/graphics/startgame.png"},
{"type": "image", "name": "imgGameBackground", "src": "resources/graphics/img_game_background.png"},
{"type": "image", "name": "imgBoardBackground", "src": "resources/graphics/img_board_bg.png"},
{"type": "image", "name": "imgLogo", "src": "resources/graphics/logo.png"},

{"type": "image", "name": "imgLeft", "src": "resources/graphics/left.png"},
{"type": "image", "name": "imgRight", "src": "resources/graphics/right.png"},
{"type": "image", "name": "imgDown", "src": "resources/graphics/down.png"},
{"type": "image", "name": "imgUp", "src": "resources/graphics/up.png"},

{"type": "image", "name": "imgLogoPansa", "src": "resources/graphics/pansacreations.png"},
{"type": "image", "name": "imgDesign", "src": "resources/graphics/design.png"},

{"type": "image", "name": "imgBlock0", "src": "resources/graphics/block_0.png"},
{"type": "image", "name": "imgBlock1", "src": "resources/graphics/block_1.png"},
{"type": "image", "name": "imgBlock2", "src": "resources/graphics/block_2.png"},
{"type": "image", "name": "imgBlock3", "src": "resources/graphics/block_3.png"},
{"type": "image", "name": "imgBlock4", "src": "resources/graphics/block_4.png"},
{"type": "image", "name": "imgBlock5", "src": "resources/graphics/block_5.png"},
{"type": "image", "name": "imgBlock6", "src": "resources/graphics/block_6.png"},

{"type": "image", "name": "img000", "src": "resources/graphics/000.png"},
{"type": "image", "name": "img001", "src": "resources/graphics/001.png"},
{"type": "image", "name": "img002", "src": "resources/graphics/002.png"},
{"type": "image", "name": "img003", "src": "resources/graphics/003.png"},
{"type": "image", "name": "img004", "src": "resources/graphics/004.png"},
{"type": "image", "name": "img005", "src": "resources/graphics/005.png"},
{"type": "image", "name": "img006", "src": "resources/graphics/006.png"},
{"type": "image", "name": "img007", "src": "resources/graphics/007.png"},
{"type": "image", "name": "img008", "src": "resources/graphics/008.png"},
{"type": "image", "name": "img009", "src": "resources/graphics/009.png"},

{"type": "image", "name": "chr0", "src": "resources/graphics/fonts/0.png"},
{"type": "image", "name": "chr1", "src": "resources/graphics/fonts/1.png"},
{"type": "image", "name": "chr2", "src": "resources/graphics/fonts/2.png"},
{"type": "image", "name": "chr3", "src": "resources/graphics/fonts/3.png"},
{"type": "image", "name": "chr4", "src": "resources/graphics/fonts/4.png"},
{"type": "image", "name": "chr5", "src": "resources/graphics/fonts/5.png"},
{"type": "image", "name": "chr6", "src": "resources/graphics/fonts/6.png"},
{"type": "image", "name": "chr7", "src": "resources/graphics/fonts/7.png"},
{"type": "image", "name": "chr8", "src": "resources/graphics/fonts/8.png"},
{"type": "image", "name": "chr9", "src": "resources/graphics/fonts/9.png"},

{"type": "image", "name": "chrA", "src": "resources/graphics/fonts/A.png"},
{"type": "image", "name": "chrB", "src": "resources/graphics/fonts/B.png"},
{"type": "image", "name": "chrC", "src": "resources/graphics/fonts/C.png"},
{"type": "image", "name": "chrD", "src": "resources/graphics/fonts/D.png"},
{"type": "image", "name": "chrE", "src": "resources/graphics/fonts/E.png"},
{"type": "image", "name": "chrF", "src": "resources/graphics/fonts/F.png"},
{"type": "image", "name": "chrG", "src": "resources/graphics/fonts/G.png"},
{"type": "image", "name": "chrH", "src": "resources/graphics/fonts/H.png"},
{"type": "image", "name": "chrI", "src": "resources/graphics/fonts/I.png"},
{"type": "image", "name": "chrJ", "src": "resources/graphics/fonts/J.png"},
{"type": "image", "name": "chrK", "src": "resources/graphics/fonts/K.png"},
{"type": "image", "name": "chrL", "src": "resources/graphics/fonts/L.png"},
{"type": "image", "name": "chrM", "src": "resources/graphics/fonts/M.png"},
{"type": "image", "name": "chrN", "src": "resources/graphics/fonts/N.png"},
{"type": "image", "name": "chrO", "src": "resources/graphics/fonts/O.png"},
{"type": "image", "name": "chrP", "src": "resources/graphics/fonts/P.png"},
{"type": "image", "name": "chrQ", "src": "resources/graphics/fonts/Q.png"},
{"type": "image", "name": "chrR", "src": "resources/graphics/fonts/R.png"},
{"type": "image", "name": "chrS", "src": "resources/graphics/fonts/S.png"},
{"type": "image", "name": "chrT", "src": "resources/graphics/fonts/T.png"},
{"type": "image", "name": "chrU", "src": "resources/graphics/fonts/U.png"},
{"type": "image", "name": "chrV", "src": "resources/graphics/fonts/V.png"},
{"type": "image", "name": "chrW", "src": "resources/graphics/fonts/W.png"},
{"type": "image", "name": "chrX", "src": "resources/graphics/fonts/X.png"},
{"type": "image", "name": "chrY", "src": "resources/graphics/fonts/Y.png"},
{"type": "image", "name": "chrZ", "src": "resources/graphics/fonts/Z.png"}

]
